### ISSUE TITLE
Request to use default pool id. 

### ISSUE THREAD

**Issue by rkothiya** [gluster/gluster-ansible-repositories#12]
When trying to use activation key manually, I did not have to use any pool id, it auto attached to the available pool but here this seems to be mandatory. 

```
TASK [gluster.repos : check if gluster_repos_pools is set] **********************************************************************************************************************************
fatal: [server1.example.com]: FAILED! => {"changed": false, "msg": "Please provide List of pool ids to attach"}
```

**Comment by pkesavap** [comment]
Ignore previous mentions , for this issue, PR yet to be created for this (if needed)

**Comment by pkesavap** [comment]
@rkothiya im not sure bout this one rinku, so if you could confirm this PR , then we can get it merged,
@gobindadas ^^

**Comment by pkesavap** [comment]
The PR is merged.
